# Site settings
title: Brian Shoemaker AWS Cloud Architect
tag_text: Brian Shoemaker
description: This profile page was created using a combination of Github, CircleCI, Jekyll, AWS S3 and AWS CloudFront for a high performance serverless website

# Build settings
markdown: kramdown
exclude: ["README.md"]
exclude: ['vendor']
sass:
  style: compressed
