# Site settings
title: Brian Shoemaker Cloud Architect
tag_text: Brian Shoemaker AWS Cloud Architect
description: This profile page was created using a combination of Github, CircleCI, Jekyll, AWS Simple Storage Service (S3) and AWS CloudFront for a 100% serverless website that is extremely low cost.

# Build settings
markdown: kramdown
exclude: ["README.md"]
exclude: ['vendor']
sass:
  style: compressed
